version: "3.7"
services:
  seasonalbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seasonalbot
    init: true

    restart: always
    depends_on:
      - redis

    environment:
      - SEASONALBOT_TOKEN
      - SEASONALBOT_DEBUG
      - SEASONALBOT_GUILD
      - SEASONALBOT_ADMIN_ROLE_ID
      - CHANNEL_DEVLOG
      - CHANNEL_SEASONALBOT_COMMANDS
      - REDIS_HOST=redis

    volumes:
      - /opt/pythondiscord/seasonalbot/log:/bot/bot/log
      - /opt/pythondiscord/seasonalbot/data:/bot/data
      - .:/bot

  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
