name: Build

on:
  workflow_run:
    workflows: ["Lint"]
    branches:
      - master
    types:
      - completed

jobs:
  build:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push'
    name: Build, Push, & Deploy Container
    runs-on: ubuntu-latest

    steps:
      # Create a commit SHA-based tag for the container repositories
      - name: Create SHA Container Tag
        id: sha_tag
        run: |
          tag=$(cut -c 1-7 <<< $GITHUB_SHA)
          echo "::set-output name=tag::$tag"

      # Check out the current repository in the `sir-lancebot` subdirectory
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: sir-lancebot

      # Check out the private "kubernetes" repository in the `kubernetes`
      # subdirectory using a GitHub Personal Access Token
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: python-discord/kubernetes
          token: ${{ secrets.REPO_TOKEN }}
          path: kubernetes

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN  }}

      # Build and push the container to the GitHub Container
      # Repository. The container will be tagged as "latest"
      # and with the short SHA of the commit.
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: sir-lancebot/
          file: sir-lancebot/Dockerfile
          push: true
          cache-from: type=registry,ref=ghcr.io/python-discord/sir-lancebot:latest
          cache-to: type=inline
          tags: |
            ghcr.io/python-discord/sir-lancebot:latest
            ghcr.io/python-discord/sir-lancebot:${{ steps.sha_tag.outputs.tag }}

      - name: Authenticate with Kubernetes
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
              kubernetes/sir-lancebot/deployment.yaml
          images: 'ghcr.io/python-discord/sir-lancebot:${{ steps.sha_tag.outputs.tag }}'
          kubectl-version: 'latest'

      # Send an informational status embed to Discord instead of the
      # standard embeds that Discord sends. This embed will contain
      # more information and we can fine tune when we actually want
      # to send an embed.
      - name: GitHub Actions Status Embed for Discord
        # This is the last step in the lint-build sequence, so always send
        # an embed, regardless of success, failure or cancelled status.
        if: always()
        uses: SebastiaanZ/github-status-embed-for-discord@v0.1.1
        with:
          # Our GitHub Actions webhook
          webhook_id: '784184528997842985'
          webhook_token: ${{ secrets.GHA_WEBHOOK_TOKEN }}

          # Workflow information
          workflow_name: ${{ github.workflow }}
          run_id: ${{ github.run_id }}
          run_number: ${{ github.run_number }}
          status: ${{ job.status }}
          actor: ${{ github.actor }}
          repository:  ${{ github.repository }}
          ref: ${{ github.ref }}
          sha: ${{ github.sha }}

          # Optional PR-information. These values will be "null" if
          # the event trigger was not PR-related.
          pr_author_login: ${{ github.event.pull_request.user.login }}
          pr_number: ${{ github.event.pull_request.number }}
          pr_title: ${{ github.event.pull_request.title }}
          pr_source: ${{ github.event.pull_request.head.label }}
